version: '3'

services:
  mysanpetedb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./20240328.06.25.21.sql:/docker-entrypoint-initdb.d/A_init.sql

  mysanpeteweb:
    build: .
    ports:
      - 420:8080
    environment:
      MySanpeteDb: user id= postgres; password=postgres; server=mysanpetedb; database= postgres;
      Domain: ${Domain}
      ClientId: ${ClientId}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      MapKey: ${MapKey}
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - mysanpetedb

  mysanpeteswag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=mysanpete.duckdns.org
      - SUBDOMAINS=www,
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS:-blahblahblah} #optional
      - STAGING=false #optional
    volumes:
      - swag-data:/config
      - ./Telemetry/nginx-default.conf:/config/nginx/site-confs/mysite.conf
    ports:
      - 6969:443
      # - 80:80 #optional
    restart: unless-stopped

volumes:
  swag-data: