version: '3'

services:
  mysanpetedb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./20240328.06.25.21.sql:/docker-entrypoint-initdb.d/A_init.sql

  mysanpeteweb:
    build: .
    ports:
      - 420:8080
    environment:
      MySanpeteDb: user id= postgres; password=postgres; server=mysanpetedb; database= postgres;
      Domain: ${Domain}
      ClientId: ${ClientId}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      MapKey: ${MapKey}
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - mysanpetedb

  mysanpeteswag:
    image: lscr.io/linuxserver/swag
    container_name: mysanpeteswag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=mysanpete.duckdns.org
      - SUBDOMAINS=www,
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS:-blahblahblah} #optional
      - STAGING=true #optional
    volumes:
      - swag-data:/config
      - ./Telemetry/nginx-default.conf:/config/nginx/site-confs/mysite.conf
    ports:
      - 6969:443
      # - 80:80 #optional
    restart: unless-stopped

  blackbox:
    image: prom/blackbox-exporter:v0.12.0
    command:
    - --config.file=/etc/blackbox/blackbox.yml
    volumes:
    - ./Telemetry/blackbox.yml:/etc/blackbox/blackbox.yml
    depends_on:
        - mysanpeteweb

  prometheus:
    image: prom/prometheus:v2.5.0
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./Telemetry/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - blackbox

  otel-collector:
    hostname: otel
    image: otel/opentelemetry-collector-contrib:0.75.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./Telemetry/otel.yml:/etc/otel-collector-config.yaml
    restart: unless-stopped

  loki:
    image: grafana/loki:2.8.0
    command: -config.file=/etc/loki/local-config.yaml
    volumes:  
      - ./Telemetry/loki.yml:/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.4.7
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - grafana-data:/var/lib/grafana
      - ./Telemetry/grafana:/etc/grafana/provisioning
    ports:
     - 3211:3000

volumes:
  grafana-data:
  swag-data: