apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: codebras
  name: my-sanpete-deployment
  labels:
    app: my-sanpete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-sanpete
  template:
    metadata:
      labels:
        app: my-sanpete
    spec:
      containers:
      - name: my-sanpete
        image: 144.17.92.12:5000/codebras/mysanpete:1
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: MySanpeteDb
          value: user id = postgres; password=postgres; server=my-sanpete-database-service; database= postgres; port= 5432
        - name: WebsiteUrl
          value: http://mysanpetekube.duckdns.org
        - name: "DOTNET_HOSTBUILDER_RELOADCONFIGONCHANGE"
          value: "false"
        - name: FeatureFlag
          value: "true"
        livenessProbe: 
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 6
          periodSeconds: 5
        readinessProbe: 
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

