apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: codebras
  name: my-sanpete-deployment
  labels:
    app: my-sanpete
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-sanpete
  template:
    metadata:
      labels:
        app: my-sanpete
    spec:
      containers:
      - name: my-sanpete
        image: 144.17.92.12:5000/codebras/mysanpete:${GITHUB_RUN_ID}
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: MySanpeteDb
          value: user id = postgres; password=postgres; server=my-sanpete-database-service; database= postgres; port= 5432
        - name: WebsiteUrl
          value: http://mysanpetekube.duckdns.org
        - name: MapKey
          value: fmCGCOVvE-xgq4gMgTxwRmKzXYFA_5HWHZ7ns0AMD-M
        - name: "DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE"
          value: "false"
        - name: FeatureFlag
          value: "true"
        livenessProbe: 
          httpGet:
              path: /healthcheck
              port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10  
          failureThreshold: 3  
          timeoutSeconds: 1  
        readinessProbe: 
          httpGet:
              path: /healthcheck
              port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
