scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://mysanpeteweb:8080/healthcheck
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: 'CollectMetrics'
    scrape_interval: 1s
    static_configs:
    - targets: ['otel-collector:3628']
