{
 "title": "Main Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"http://mysanpeteweb:8080/healthcheck\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(up{instance=\"http://mysanpeteweb:8080/healthcheck\"}[1w])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "All errors happening",
   "type": "logs",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"MySanpete\"} |= `exception`"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"MySanpete\"} |= \"exception\"[30m]))"
    }
   ]
  },
  { "title": "Unique For Us", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Page Hits",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"CollectMetrics\", __name__=~\"(podcast|event|voucher|blog|business)_page_hit_count\"}"
    }
   ]
  },
  {
   "title": "How long does it take load images",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "image_retrieval_bucket{le=\"100\"}",
     "legendFormat": "Image_data"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total Storage Taken (bytes)",
   "type": "bargauge",
   "description": "yikes",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_storage_taken", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total users on home page",
   "type": "stat",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "users_on_home_page_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} |= ``"
    }
   ]
  }
 ]
}