name: backup database
on: 
  - workflow_dispatch
jobs:
  backup:
    runs-on: MySanpete
    steps:
      - name: backup
        run: |
          mkdir -p /home/enoch/dumps

          CONTAINER_NAME=$(kubectl -n codebras get pods --no-headers -o custom-columns=":metadata.name" | grep my-sanpete-database-deployment)

          kubectl -n codebras exec -t $CONTAINER_NAME -- \
            pg_dumpall -c -U postgres \
            > /home/enoch/dumps/mysanpetedump.sql