name: Pull Request Environment
on: 
  pull_request:
   types: [closed]
jobs:
  deploy_to_kubernetes:
    runs-on: MySanpete
    steps: 
      - name: deploy kubernetes environment
        run: |
          export PULL_REQUEST_ID=${{ github.event.pull_request.number }}
          export NAMESPACE="mysanpete-pr-${PULL_REQUEST_ID}"

          kubectl delete namespace ${NAMESPACE}