name: Pull Request Environment
on: 
  pull_request:
   types: [opened]
jobs:
  deploy_to_kubernetes:
    runs-on: MySanpete
    steps: 
      - name: check out code
        uses: actions/checkout@v4
      - name: deploy kubernetes environment
        run: |
          export PULL_REQUEST_ID=${{ github.event.pull_request.number }}
          kubectl create namespace mysanpete-pr-$PULL_REQUEST_ID